name: Publish MartiX.Result.AspNetCore and FluentValidation to Nuget.org

on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish MartiX.Result.AspNetCore to NuGet
        run: |
          rm -rf nuget/
          dotnet pack --no-build src/MartiX.Result.AspNetCore/MartiX.Result.AspNetCore.csproj --configuration Release --output nuget
          dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json

      - name: Publish MartiX.Result.FluentValidation to NuGet
        run: |
          rm -rf nuget/
          dotnet pack --no-build src/MartiX.Result.FluentValidation/MartiX.Result.FluentValidation.csproj --configuration Release --output nuget
          dotnet nuget push nuget/*.nupkg -k '${{ secrets.NUGET_API_KEY }}' --skip-duplicate -s https://api.nuget.org/v3/index.json
